# Generated by Django 4.1.7 on 2023-03-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_data_account_data_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_user',
            name='image_profile',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
