# Generated by Django 4.1.7 on 2023-05-06 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=50, unique=True)),
                ('list_id', models.IntegerField()),
                ('list_content', models.JSONField(default=list)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userlists',
            constraint=models.UniqueConstraint(fields=('author', 'list_id'), name='unique_list_id'),
        ),
        migrations.AddConstraint(
            model_name='userlists',
            constraint=models.UniqueConstraint(fields=('list_id',), name='unique_list_id2'),
        ),
    ]
