# Generated by Django 4.1.7 on 2023-05-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userlists',
            name='unique_list_id2',
        ),
        migrations.RemoveField(
            model_name='userlists',
            name='id',
        ),
        migrations.AlterField(
            model_name='userlists',
            name='list_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
