# Generated by Django 4.1.7 on 2023-05-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserList', '0002_remove_userlists_unique_list_id2_remove_userlists_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlists',
            name='list_name',
            field=models.CharField(max_length=50),
        ),
    ]
