# Generated by Django 4.1.7 on 2023-03-22 10:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_rename_account_data_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data_account',
            new_name='data_user',
        ),
    ]
