# Generated by Django 4.1.7 on 2023-05-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_data_user_image_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_user',
            name='age',
        ),
        migrations.AddField(
            model_name='data_user',
            name='nsfw_content',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
